### ISSUE TITLE
Extension doesn't work on fresh install

### ISSUE THREAD

**Issue by Cudochi** [xiyaowong/coc-symbol-line#12]
Right after installing the extension by doing `:CocInstall coc-symbol-line` with no specific config.
Error message on Neovim start : 
```
[coc.nvim]: UnhandledRejection: Vim(highlight):E669: Unprintable character in group name
Error: request error on "nvim_command" - Vim(highlight):E669: Unprintable character in group name
    at Object.activate (/home/heures/.config/coc/extensions/node_modules/coc-symbol-line/lib/index.js:5663:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/bob/.config/nvim/bundle/coc.nvim/build/index.js:68882:27
Press ENTER or type command to continue
```
Coc.Nvim is up-to-date. List of my other extensions : 
`let g:coc_global_extensions = ['coc-highlight', 'coc-discord', 'coc-snippets', 'coc-lists', 'coc-lua', 'coc-tsserver', 'coc-pyright', 'coc-clangd', 'coc-json', 'coc-sql', 'coc-vimlsp', 'coc-html', 'coc-java']`

**Comment by xiyaowong** [comment]
Can't reproduce.

**Comment by xiyaowong** [comment]
reopen when you still have this issue

**Comment by younger-1** [comment]
Same problem with nvim at mac

```log
[coc.nvim]: UnhandledRejection: Vim(highlight):E669: Unprintable character in group name
Error: request error on "nvim_command" - Vim(highlight):E669: Unprintable character in group name
    at Object.activate (/Users/young/.config/coc/extensions/node_modules/coc-symbol-line/lib/index.js:5663:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/young/.local/share/nvim/lazy/coc.nvim/build/index.js:255:33099
```

Looks like caused by the ^M char in each line's ending and nvim take it as part of hl-group name
![图片](https://user-images.githubusercontent.com/45989017/226679926-2214c5b4-cdc4-4f2d-996b-cf302799a7ca.png)

**Comment by xiyaowong** [comment]
Don't know how to produce this issue.
Can you run this file https://github.com/xiyaowong/coc-symbol-line/blob/main/plugin/coc_symbol_line.vim  manually? @younger-1

**Comment by younger-1** [comment]
> Don't know how to produce this issue. Can you run this file https://github.com/xiyaowong/coc-symbol-line/blob/main/plugin/coc_symbol_line.vim manually? @younger-1

Strangely, if I clone the plugin and run the file manually, everything is fine.

**Comment by younger-1** [comment]
@xiyaowong I am sure the problem was caused by the packaged nodejs plugin files using DOS `fileformat`. After convert them to UNIX (`set ff=unix`), it works normally.

**Comment by RedBeard0531** [comment]
Specifically, I had to `ff=unix` and save both of the `.vim` files (the plugin/ and autoload/ ones). Did the npm packaged files change line ending recently? Or perhaps there was a recent change to neovim-git to break loading `ff=dos` format vimscript files?

**Comment by xiyaowong** [comment]
Please check if this issue has been fixed.

**Comment by younger-1** [comment]
> Please check if this issue has been fixed.

Fixed. Thanks!
