### ISSUE TITLE
[Question] Why filter the callback symbols?

### ISSUE THREAD

**Issue by hexh250786313** [xiyaowong/coc-symbol-line#2]
https://github.com/xiyaowong/coc-symbol-line/blob/352bfb46ed8a9f0df857f7b45ff513c601960448/src/index.ts#L48

What is the purpose for it? I think it'd better to show the callback symbols like what VSCode does.

Or will there be a configurable coc option to filter some symbol kind?

**Comment by xiyaowong** [comment]
changed
