### ISSUE TITLE
[Question] Why it filter the parent symbols in nested variables?

### ISSUE THREAD

**Issue by hexh250786313** [xiyaowong/coc-symbol-line#4]
I think it should act like VScode showing all nodes in nested variables

https://github.com/xiyaowong/coc-symbol-line/blob/e5aae41aa6aa69de881e7e1b0c4ef08cc315d3bb/src/index.ts#L74

![image](https://user-images.githubusercontent.com/26080416/174048627-999dbacb-dca7-4749-a15f-8bfbc5eb814e.png)

![image](https://user-images.githubusercontent.com/26080416/174050398-c25bcee4-03be-426f-9f1f-eb012d90574e.png)

**Comment by xiyaowong** [comment]
I think it will be more concise, and I was referring to vscode, maybe vscode modified or different treatment of different languages

**Comment by hexh250786313** [comment]
I have no idea about other languages but typescript. It would be a big deal with the parents nodes not showing in nested variables in some frameworks like React (React Hooks specifically).

So there will be any plan to solve the issue?

**Comment by hexh250786313** [comment]
Maybe other IDEs like vscode give the solution. We should take a look.

**Comment by xiyaowong** [comment]
yes
