### ISSUE TITLE
display the dictionary name when my cursor is in the dictionary

### ISSUE THREAD

**Issue by zgpio** [xiyaowong/coc-symbol-line#5]
![image](https://user-images.githubusercontent.com/19503791/176356184-119fc019-d517-4337-b6eb-3f35c4d2ac94.png)

I want to display the dictionary name when my cursor is in the dictionary

**Comment by xiyaowong** [comment]
![image](https://user-images.githubusercontent.com/47070852/176382412-22d0d39d-3301-46da-80af-b6ac8cdee43c.png)

As you can see, pyright doesn't return the full range
