### ISSUE TITLE
Lightline configuration

### ISSUE THREAD

**Issue by wandering-tales** [xiyaowong/coc-symbol-line#6]
It's not actually clear to me from the README how to integrate it with the [lightline](https://github.com/itchyny/lightline.vim) plugin.

**Comment by xiyaowong** [comment]
![image](https://user-images.githubusercontent.com/47070852/182396910-cdb2f4e7-4dfb-4da6-90da-3f286e00b6f7.png)

I haven't used lightline, you can submit issue to lightline

**Comment by wandering-tales** [comment]
I came out with a similar configuration

```vim
let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \           [ 'cocstatus', 'currentfunction', 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'tabline': {
      \   'left': [ ['buffers', 'symbol'] ],
      \   'right': [ ['close'] ]
      \ },
      \ 'component_expand': {
      \   'buffers': 'lightline#bufferline#buffers'
      \ },
      \ 'component_type': {
      \   'buffers': 'tabsel'
      \ },
      \ 'component_function': {
      \   'filetype': 'MyFiletype',
      \   'fileformat': 'MyFileformat',
      \   'gitbranch': 'FugitiveHead',
      \   'cocstatus': 'coc#status',
      \   'currentfunction': 'CocCurrentFunction',
      \   'symbol': 'CocSymbolLine'
      \ },
      \ }

function! CocSymbolLine()
    return get(b:, 'coc_symbol_line', '')
endfunction
```

but what I have obtained is the same garbled output. I guess lightline expects thinks formatted in a certain way, and your provided function is simply not meant to be used with that.

I also see that in the README you mentions that _Highlights_ should be setup before activating this extension:
- `CocSymbolLine`
- `CocSymbolLineSeparator`
- `CocSymbolLineEllipsis`

What does that mean, exactly?

**Comment by xiyaowong** [comment]
@wandering-tales https://github.com/xiyaowong/coc-symbol-line/blob/d313b04fcb76424c91ec1cc417f3845994d0cc57/plugin/coc_symbol_line.vim#L31

**Comment by xiyaowong** [comment]
make sure you custom highlights before this line. actually, you can ignore this,
