### ISSUE TITLE
Breaks nvim when updatetime>500

### ISSUE THREAD

**Issue by lygamac** [xiyaowong/coc-symbol-line#7]
Minimal vimrc:
```vim
set updatetime=501
autocmd CursorHold * echo strftime('%c')

call plug#begin('~/.local/share/nvim/plugged')
	Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

let g:coc_global_extensions = [
			\ 'coc-symbol-line'
			\ ]
```

When `updatetime = 500`, CursorHold or any other call such as the one used in this repo `%{%get(b:, "coc_symbol_line", "")%}` takes 10 ~ 20 seconds to respond.

For `updatetime = 501` or greater, CursorHold will take >5 minutes to get triggered, same for other functions. But executing `CocUninstall coc-symbol-line`, everything responds as expected without restarting.

`updatetime=499` or lower behaves normally.

**Comment by xiyaowong** [comment]
@lygamac Can you try this https://github.com/antoinemadec/FixCursorHold.nvim
